const styleOptions = ['Style: Bold', 'Style: Italic', 'Style: Underline', 'Style: Strike Through', 'Style: Format Painter'];

const mathFormulaOptions = [
    'Formula: ABS',
    'Formula: ABS',
    'Formula: ACOS',
    'Formula: ACOSH',
    'Formula: ACOT',
    'Formula: ACOTH',
    'Formula: AGGREGATE',
    'Formula: ASIN',
    'Formula: ASINH',
    'Formula: ATAN',
    'Formula: ATAN2',
    'Formula: ATANH',
    'Formula: BESSELI',
    'Formula: BESSELJ',
    'Formula: BESSELK',
    'Formula: BESSELY',
    'Formula: CEILING',
    'Formula: COMBIN',
    'Formula: COMBINA',
    'Formula: CONVERT',
    'Formula: COS',
    'Formula: COSH',
    'Formula: COT',
    'Formula: COTH',
    'Formula: COUNTBLANK',
    'Formula: COUNTIF',
    'Formula: COUNTIFS',
    'Formula: DEGREES',
    'Formula: DELTA',
    'Formula: ERF',
    'Formula: ERFC',
];

const financialFormulaOptions = [
    'Formula: ACCRINT',
    'Formula: ACCRINTM',
    'Formula: AMORDEGRC',
    'Formula: AMORLINC',
    'Formula: COUPDAYBS',
    'Formula: COUPDAYS',
    'Formula: COUPDAYSNC',
    'Formula: COUPNCD',
    'Formula: COUPNUM',
    'Formula: COUPPCD',
    'Formula: CUMIPMT',
    'Formula: CUMPRINC',
    'Formula: CURRENCY',
    'Formula: DB',
    'Formula: DDB',
    'Formula: DISC',
    'Formula: DOLLARDE',
    'Formula: DOLLARFR',
    'Formula: DURATION',
    'Formula: EFFECT',
    'Formula: FV',
    'Formula: FVSCHEDULE',
    'Formula: INTRATE',
    'Formula: IPMT',
    'Formula: IRR',
    'Formula: ISPMT',
    'Formula: MDURATION',
    'Formula: MIRR',
    'Formula: NOMINAL',
    'Formula: NPER',
];

const spreadSheetFormulaOptions = [
    'Formula: ADDRESS',
    'Formula: AREAS',
    'Formula: BOTTOM',
    'Formula: CHOOSE',
    'Formula: COLUMN',
    'Formula: COLUMNS',
    'Formula: ERRORTYPE',
    'Formula: HLOOKUP',
    'Formula: HYPERLINK',
    'Formula: IMAGE',
    'Formula: IMPORTRANGE',
    'Formula: INDEX',
    'Formula: INDIRECT',
    'Formula: LAMBDA',
    'Formula: LET',
    'Formula: LOOKUP',
    'Formula: MATCH',
    'Formula: OFFSET',
    'Formula: ROW',
    'Formula: ROWS',
    'Formula: SEQUENCE',
    'Formula: SHEET',
    'Formula: SORT',
    'Formula: SORTBY',
    'Formula: TOP',
    'Formula: VLOOKUP',
    'Formula: XLOOKUP',
    'Formula: XMATCH',
];

const logicalFormulaOptions = [
    'Formula: AND',
    'Formula: FALSE',
    'Formula: FILTER',
    'Formula: IF',
    'Formula: IFERROR',
    'Formula: IFNA',
    'Formula: IFS',
    'Formula: NOT',
    'Formula: OR',
    'Formula: SWITCH',
    'Formula: TRUE',
    'Formula: XOR',
];

const numberConversionFormulaOptions = [
    'Formula: ARABIC',
    'Formula: BIN2DEC',
    'Formula: BIN2HEX',
    'Formula: BIN2OCT',
    'Formula: DEC2BIN',
    'Formula: DEC2HEX',
    'Formula: DEC2OCT',
    'Formula: DECIMAL',
    'Formula: HEX2BIN',
    'Formula: HEX2DEC',
    'Formula: HEX2OCT',
    'Formula: OCT2BIN',
    'Formula: OCT2DEC',
    'Formula: OCT2HEX',
    'Formula: ROMAN',
];

const textFormulaOptions = [
    'Formula: BASE',
    'Formula: CHAR',
    'Formula: CLEAN',
    'Formula: CODE',
    'Formula: CONCATENATE',
    'Formula: DOLLAR',
    'Formula: EXACT',
    'Formula: FIND',
    'Formula: FIXED',
    'Formula: LEFT',
    'Formula: LEN',
    'Formula: LOWER',
    'Formula: MID',
    'Formula: NUMBERVALUE',
    'Formula: PROPER',
];

export let searchResults = [
    {
        searchQuery: 'style',
        searchSynonyms: ['format', 'design'],
        searchResults: styleOptions,
    },
    {
        searchQuery: 'formula',
        searchSynonyms: ['equation', 'operation', '='],
        searchResults: [
            ...mathFormulaOptions,
            ...financialFormulaOptions,
            ...spreadSheetFormulaOptions,
            ...logicalFormulaOptions,
            ...numberConversionFormulaOptions,
            ...textFormulaOptions,
        ],
    },
    {
        searchQuery: 'math',
        searchSynonyms: ['arithmetic'],
        searchResults: mathFormulaOptions,
    },
    {
        searchQuery: 'finance',
        searchSynonyms: ['financial'],
        searchResults: financialFormulaOptions,
    },
    {
        searchQuery: 'spreadsheet',
        searchSynonyms: ['sheet'],
        searchResults: spreadSheetFormulaOptions,
    },
    {
        searchQuery: 'logical',
        searchSynonyms: ['mind'],
        searchResults: logicalFormulaOptions,
    },
    {
        searchQuery: 'numeric',
        searchSynonyms: ['number', 'conversion'],
        searchResults: numberConversionFormulaOptions,
    },
    {
        searchQuery: 'text',
        searchSynonyms: ['writing'],
        searchResults: textFormulaOptions,
    },
];
